[package]
name = "tesseract-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
fjall = "2"
axum = "0.7"
k8s-openapi = { version = "0.23", features = ["v1_31"] }